#!/bin/sh -eux

export DEBIAN_FRONTEND=noninteractive

echo "install docker dependencies"
apt-get -y install apt-transport-https ca-certificates curl gnupg lsb-release

echo "install docker archive keyring"
keyring_url="https://download.docker.com/linux/debian/gpg";
if command -v curl >/dev/null 2>&1; then
    curl --fail --location --silent --show-error "$keyring_url" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg;
else
    echo "Cannot download docker archive keyring";
    exit 1;
fi

echo "add docker apt repository"
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get -y update

echo "install docker"
apt-get -y install docker-ce docker-ce-cli containerd.io

adduser vagrant docker

echo "fetch cassandra image"
docker pull cassandra:4.0.1
